server:
  port: 8080
spring:
  application:
    name: saudacao-service
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: qa
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
saudacao-service:
  saudacao: "Olá"
  default-value: "mundao"    