server:
  port: 8888
spring:
  application:
    name: abimael-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abimaelrsergio/abimael-config-server
          #username: meuusername
          #password: minhasenha
          default-label: main
          search-paths:
          - 'saudacoes-server'